# Generated by Django 4.2.1 on 2023-05-28 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('rut', models.CharField(max_length=15, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=9, verbose_name='Telefono')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('vivienda', models.IntegerField(choices=[(1, 'Casa con patio Grande'), (2, 'Casa con Patio Pequeño'), (3, 'Casa sin patio'), (4, 'Departamento')])),
            ],
        ),
    ]
